export const RETRIEVE_USER_PROFILE_REQUEST = 'RETRIEVE_USER_PROFILE_REQUEST';
export const RETRIEVE_USER_PROFILE_SUCCESS = 'RETRIEVE_USER_PROFILE_SUCCESS';
export const RETRIEVE_USER_PROFILE_ERROR = 'RETRIEVE_USER_PROFILE_ERROR';
export const RETRIEVE_USER_PROFILE_RESET = 'RETRIEVE_USER_PROFILE_RESET';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';
export const UPDATE_USER_PROFILE_RESET = 'UPDATE_USER_PROFILE_RESET';

export const UPDATE_NOTIFICATION_PROFILE_REQUEST = 'UPDATE_NOTIFICATION_PROFILE_REQUEST';
export const UPDATE_NOTIFICATION_PROFILE_SUCCESS = 'UPDATE_NOTIFICATION_PROFILE_SUCCESS';
export const UPDATE_NOTIFICATION_PROFILE_ERROR = 'UPDATE_NOTIFICATION_PROFILE_ERROR';
export const UPDATE_NOTIFICATION_PROFILE_RESET = 'UPDATE_NOTIFICATION_PROFILE_RESET';

export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR';
export const DELETE_PROFILE_RESET = 'DELETE_PROFILE_RESET';
