export const RETRIEVE_PAYMENT_REQUEST = 'RETRIEVE_PAYMENT_REQUEST';
export const RETRIEVE_PAYMENT_SUCCESS = 'RETRIEVE_PAYMENT_SUCCESS';
export const RETRIEVE_PAYMENT_ERROR = 'RETRIEVE_PAYMENT_ERROR';
