export const RETRIEVE_PAYMENT_REQUEST = 'RETRIEVE_PAYMENT_REQUEST';
export const RETRIEVE_PAYMENT_SUCCESS = 'RETRIEVE_PAYMENT_SUCCESS';
export const RETRIEVE_PAYMENT_ERROR = 'RETRIEVE_PAYMENT_ERROR';

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR';

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';

export const SET_RESERVATION_COMPLETE_REQUEST = 'SET_RESERVATION_COMPLETE_REQUEST';
export const SET_RESERVATION_COMPLETE_SUCCESS = 'SET_RESERVATION_COMPLETE_SUCCESS';
export const SET_RESERVATION_COMPLETE_ERROR = 'SET_RESERVATION_COMPLETE_ERROR';
