export const RESERVATION_CREATION_REQUEST = 'RESERVATION_CREATION_REQUEST';
export const RESERVATION_CREATION_SUCCESS = 'RESERVATION_CREATION_SUCCESS';
export const RESERVATION_CREATION_ERROR = 'RESERVATION_CREATION_ERROR';
