# Generated by Django 4.0.2 on 2022-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='after_tax_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
