# Generated by Django 4.0.2 on 2022-02-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_billdetail_after_tax_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=255)),
                ('menu_item_description', models.TextField()),
                ('menu_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item_image', models.ImageField(upload_to='menu-item-image/')),
                ('menu_item_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menu')),
            ],
        ),
    ]
