# Generated by Django 4.0.2 on 2022-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderiteminorder_remove_order_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='num_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_cuisine',
            field=models.CharField(choices=[('WS', 'Western'), ('CH', 'Chinese'), ('JP', 'Japanese'), ('KR', 'Korean'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='restaurant-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_rating',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('HC', 'Kopitiam'), ('CF', 'Cafe'), ('BA', 'Bar'), ('HE', 'High End Restaurant'), ('ME', 'Medium End Restaurant'), ('BR', 'Budget Restaurant'), ('FF', 'Fast Food Restaurant'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
