# Generated by Django 4.0.2 on 2022-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_restaurant_num_clicks_restaurant_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
