export const RESERVATION_GET_ALL_RESERVATION_REQUEST = 'RESERVATION_GET_ALL_RESERVATION_REQUEST';
export const RESERVATION_GET_ALL_RESERVATION_SUCCESS = 'RESERVATION_GET_ALL_RESERVATION_SUCCESS';
export const RESERVATION_GET_ALL_RESERVATION_ERROR = 'RESERVATION_GET_ALL_RESERVATION-ERROR';

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS';
export const RESERVATION_DELETE_ERROR = 'RESERVATION_DELETE_ERROR';

export const RESERVATION_JOIN_REQUEST = 'RESERVATION_JOIN_REQUEST';
export const RESERVATION_JOIN_SUCCESS = 'RESERVATION_JOIN_SUCCESS';
export const RESERVATION_JOIN_ERROR = 'RESERVATION_JOIN_ERROR';

export const RESERVATION_REMOVE_REQUEST = 'RESERVATION_REMOVE_REQUEST';
export const RESERVATION_REMOVE_SUCCESS = 'RESERVATION_REMOVE_SUCCESS';
export const RESERVATION_REMOVE_ERROR = 'RESERVATION_REMOVE_ERROR';
