export const RESERVATION_GET_ALL_COMPLETED_REQUEST = 'RESERVATION_GETALLCOMPLETED_REQUEST';
export const RESERVATION_GET_ALL_COMPLETED_SUCCESS = 'RESERVATION_GETALLCOMPLETED_SUCCESS';
export const RESERVATION_GET_ALL_COMPLETED_ERROR = 'RESERVATION_GETALLCOMPLETED_ERROR';

export const RESERVATION_GET_ALL_ACTIVE_REQUEST = 'RESERVATION_GETALLACTIVE_REQUEST';
export const RESERVATION_GET_ALL_ACTIVE_SUCCESS = 'RESERVATION_GETALLACTIVE_SUCCESS';
export const RESERVATION_GET_ALL_ACTIVE_ERROR = 'RESERVATION_GETALLACTIVE_ERROR';

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_UPDATE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS';
export const RESERVATION_DELETE_ERROR = 'RESERVATION_UPDATE_ERROR';

export const RESERVATION_JOIN_REQUEST = 'RESERVATION_UPDATE_REQUEST';
export const RESERVATION_JOIN_SUCCESS = 'RESERVATION_UPDATE_SUCCESS';
export const RESERVATION_JOIN_ERROR = 'RESERVATION_UPDATE_ERROR';

export const RESERVATION_REMOVE_REQUEST = 'RESERVATION_REMOVE_REQUEST';
export const RESERVATION_REMOVE_SUCCESS = 'RESERVATION_REMOVE_SUCCESS';
export const RESERVATION_REMOVE_ERROR = 'RESERVATION_REMOVE_ERROR';
