/* eslint-disable linebreak-style */

// Defines what the states can do
export const RETRIEVE_RESTAURANTS_REQUEST = 'RETRIEVE_RESTAURANTS_REQUEST';
export const RETRIEVE_RESTAURANTS_SUCCESS = 'RETRIEVE_RESTAURANTS_SUCCESS';
export const RETRIEVE_RESTAURANTS_ERROR = 'RETRIEVE_RESTAURANTS_ERROR';
export const RETRIEVE_RESTAURANTS_RESET = 'RETRIEVE_RESTAURANTS_RESET';
