export const RETRIEVE_PRE_ORDER_ITEMS_REQUEST = 'RETRIEVE_PRE_ORDER_ITEMS_REQUEST';
export const RETRIEVE_PRE_ORDER_ITEMS_SUCCESS = 'RETRIEVE_PRE_ORDER_ITEMS_SUCCESS';
export const RETRIEVE_PRE_ORDER_ITEMS_ERROR = 'RETRIEVE_PRE_ORDER_ITEMS_ERROR';

export const ADD_PRE_ORDER_ITEM_REQUEST = 'ADD_PRE_ORDER_ITEM_REQUEST';
export const ADD_PRE_ORDER_ITEM_SUCCESS = 'ADD_PRE_ORDER_ITEM_SUCCESS';
export const ADD_PRE_ORDER_ITEM_ERROR = 'ADD_PRE_ORDER_ITEM_ERROR';

export const REMOVE_PRE_ORDER_ITEM_REQUEST = 'REMOVE_PRE_ORDER_ITEM_REQUEST';
export const REMOVE_PRE_ORDER_ITEM_SUCCESS = 'REMOVE_PRE_ORDER_ITEM_SUCCESS';
export const REMOVE_PRE_ORDER_ITEM_ERROR = 'REMOVE_PRE_ORDER_ITEM_ERROR';

export const UPDATE_PRE_ORDER_ITEM_REQUEST = 'UPDATE_PRE_ORDER_ITEM_REQUEST';
export const UPDATE_PRE_ORDER_ITEM_SUCCESS = 'UPDATE_PRE_ORDER_ITEM_SUCCESS';
export const UPDATE_PRE_ORDER_ITEM_ERROR = 'UPDATE_PRE_ORDER_ITEM_ERROR';

export const RETRIEVE_MENU_REQUEST = 'RETRIEVE_MENU_REQUEST';
export const RETRIEVE_MENU_SUCCESS = 'RETRIEVE_MENU_SUCCESS';
export const RETRIEVE_MENU_ERROR = 'RETRIEVE_MENU_ERROR';
