export const RESERVATION_UPDATE_REQUEST = 'RESERVATION_UPDATE_REQUEST';
export const RESERVATION_UPDATE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS';
export const RESERVATION_UPDATE_ERROR = 'RESERVATION_UPDATE_ERROR';

export const RESERVATION_GET_REQUEST = 'RESERVATION_GET_REQUEST';
export const RESERVATION_GET_SUCCESS = 'RESERVATION_GET_SUCCESS';
export const RESERVATION_GET_ERROR = 'RESERVATION_GET_ERROR';
