export const GET_PROPORTIONS_REQUEST = 'GET_PROPORTIONS_REQUEST';
export const GET_PROPORTIONS_SUCCESS = 'GET_PROPORTIONS_SUCCESS';
export const GET_PROPORTIONS_ERROR = 'GET_PROPORTIONS_ERROR';

export const SPLIT_PROPORTIONS_REQUEST = 'SPLIT_PROPORTIONS_REQUEST';
export const SPLIT_PROPORTIONS_SUCCESS = 'SPLIT_PROPORTIONS_SUCCESS';
export const SPLIT_PROPORTIONS_ERROR = 'SPLIT_PROPORTIONS_ERROR';
