export const RESERTAURANT_GET_REQUEST = 'RESERTAURANT_GET_REQUEST';
export const RESERTAURANT_GET_SUCCESS = 'RESERTAURANT_GET_SUCCESS';
export const RESERTAURANT_GET_ERROR = 'RESERTAURANT_GET_ERROR';
