export const RETRIEVE_PAYMENT_REQUEST = 'RETRIEVE_PAYMENT_REQUEST';
export const RETRIEVE_PAYMENT_SUCCESS = 'RETRIEVE_PAYMENT_SUCCESS';
export const RETRIEVE_PAYMENT_ERROR = 'RETRIEVE_PAYMENT_ERROR';

export const SUBMIT_PROPORTION_REQUEST = 'SUBMIT_PROPORTION_REQUEST';
export const SUBMIT_PROPORTION_SUCCESS = 'SUBMIT_PROPORTION_SUCCESS';
export const SUBMIT_PROPORTION_ERROR = 'SUBMIT_PROPORTION_ERROR';
